name: Continous integration
on: [push]
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up latest Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # This will pick the latest stable 3.x version (e.g., 3.12, 3.13, etc.)
    - name: Display Python version
      run: python --version
      env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        nose2 tests
